[features]
seeds = false
skip-lint = false
[programs.localnet]
trustify_anchor = "5b1fLmZgEvCS6U4KaZ9gWcdqaWyHhJDVJuw2uuQJnNbB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/vogiaan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.28.0"
solana_version = "1.16.18"
